package bypass

import (
	"github.com/th3-bl1nd3r/java-path-scanner/pkg/httpclient"
)

// Variant is a generated bypass URL variant to test.
type Variant struct {
	Path      string
	Technique string
	Headers   map[string]string
}

// Attempt represents a single bypass attempt and its result.
type Attempt struct {
	OriginalPath      string
	BypassPath        string
	Technique         string
	URL               string
	OriginalStatus    int
	BypassStatus      int
	OriginalLength    int
	BypassLength      int
	ContentSimilarity float64
	HeadersUsed       map[string]string
	Success           bool
	Response          *httpclient.Response
}

// StatusChanged returns true if the bypass changed the status code.
func (a *Attempt) StatusChanged() bool {
	return a.BypassStatus != a.OriginalStatus
}

// SignificantContentDiff returns true if content differs significantly.
func (a *Attempt) SignificantContentDiff() bool {
	return a.ContentSimilarity < 0.7 && a.BypassLength > 50
}

// Result contains all bypass attempts for a single path.
type Result struct {
	Target             string
	OriginalPath       string
	OriginalStatus     int
	Attempts           []*Attempt
	SuccessfulBypasses []*Attempt
}

// Bypassed returns true if any bypass succeeded.
func (r *Result) Bypassed() bool {
	return len(r.SuccessfulBypasses) > 0
}
