package output

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

// MarkdownWriter generates a markdown report.
type MarkdownWriter struct {
	path    string
	results []*TargetResult
}

// NewMarkdownWriter creates a new markdown writer.
func NewMarkdownWriter(path string) *MarkdownWriter {
	return &MarkdownWriter{path: path}
}

// OnFinding is a no-op (markdown is batched).
func (mw *MarkdownWriter) OnFinding(_ *Finding) {}

// OnTargetStart is a no-op.
func (mw *MarkdownWriter) OnTargetStart(_ string) {}

// OnTargetDone collects results for the final report.
func (mw *MarkdownWriter) OnTargetDone(result *TargetResult) {
	mw.results = append(mw.results, result)
}

// Flush writes the complete markdown report.
func (mw *MarkdownWriter) Flush() error {
	if len(mw.results) == 0 {
		return nil
	}

	var sb strings.Builder
	totalFindings := 0
	summary := ScanSummary{}

	for _, r := range mw.results {
		totalFindings += len(r.Findings)
		for _, f := range r.Findings {
			switch f.Severity {
			case "critical":
				summary.Critical++
			case "high":
				summary.High++
			case "medium":
				summary.Medium++
			case "low":
				summary.Low++
			default:
				summary.Info++
			}
		}
	}

	sb.WriteString("# Java Path Scanner Report\n\n")
	sb.WriteString(fmt.Sprintf("**Generated:** %s  \n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("**Targets:** %d  \n", len(mw.results)))
	sb.WriteString(fmt.Sprintf("**Total Findings:** %d  \n\n", totalFindings))

	// Summary
	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Severity | Count |\n|----------|-------|\n")
	sb.WriteString(fmt.Sprintf("| Critical | %d |\n", summary.Critical))
	sb.WriteString(fmt.Sprintf("| High | %d |\n", summary.High))
	sb.WriteString(fmt.Sprintf("| Medium | %d |\n", summary.Medium))
	sb.WriteString(fmt.Sprintf("| Low | %d |\n", summary.Low))
	sb.WriteString(fmt.Sprintf("| Info | %d |\n\n", summary.Info))

	// Per-target
	for _, r := range mw.results {
		sb.WriteString(fmt.Sprintf("## %s\n\n", r.Target))

		if r.Fingerprint != nil {
			techs := r.Fingerprint.DetectedTechs()
			if len(techs) > 0 {
				sb.WriteString(fmt.Sprintf("**Technologies:** %s  \n", strings.Join(techs, ", ")))
			}
			if r.Fingerprint.WAFDetected != "" {
				sb.WriteString(fmt.Sprintf("**WAF:** %s  \n", r.Fingerprint.WAFDetected))
			}
			sb.WriteString("\n")
		}

		if len(r.Findings) == 0 {
			sb.WriteString("No findings.\n\n")
			continue
		}

		// Sort by severity
		sorted := make([]*Finding, len(r.Findings))
		copy(sorted, r.Findings)
		sort.Slice(sorted, func(i, j int) bool {
			return sorted[i].SeverityRank() < sorted[j].SeverityRank()
		})

		// Summary table
		sb.WriteString("| # | Severity | Path | Status | Title |\n")
		sb.WriteString("|---|----------|------|--------|-------|\n")
		for i, f := range sorted {
			title := f.Title
			if len(title) > 60 {
				title = title[:60] + "..."
			}
			sb.WriteString(fmt.Sprintf("| %d | %s | `%s` | %d | %s |\n",
				i+1, f.Severity, f.Path, f.StatusCode, title))
		}
		sb.WriteString("\n")

		// Detailed findings
		sb.WriteString("### Detailed Findings\n\n")
		for _, f := range sorted {
			sb.WriteString(fmt.Sprintf("#### [%s] %s\n\n", strings.ToUpper(f.Severity), f.Title))
			sb.WriteString(fmt.Sprintf("- **URL:** `%s`\n", f.URL))
			sb.WriteString(fmt.Sprintf("- **Status:** %d\n", f.StatusCode))
			sb.WriteString(fmt.Sprintf("- **Size:** %d bytes\n", f.ContentLength))
			sb.WriteString(fmt.Sprintf("- **Technology:** %s\n", f.Technology))

			if f.BypassTechnique != "" {
				sb.WriteString(fmt.Sprintf("- **Bypass:** %s\n", f.BypassTechnique))
			}
			if len(f.CVEs) > 0 {
				sb.WriteString(fmt.Sprintf("- **CVEs:** %s\n", strings.Join(f.CVEs, ", ")))
			}
			if f.Description != "" {
				sb.WriteString(fmt.Sprintf("\n%s\n", f.Description))
			}
			if len(f.SecretsFound) > 0 {
				sb.WriteString("\n**Secrets Found:**\n")
				for _, s := range f.SecretsFound {
					sb.WriteString(fmt.Sprintf("- `%s`\n", s))
				}
			}
			if f.Remediation != "" {
				sb.WriteString(fmt.Sprintf("\n**Remediation:** %s\n", f.Remediation))
			}
			sb.WriteString("\n---\n\n")
		}
	}

	sb.WriteString("\n*Generated by Java Path Scanner v1.0 — For authorized security testing only*\n")

	return os.WriteFile(mw.path, []byte(sb.String()), 0644)
}
